### ISSUE TITLE
Creating a function to select a given number of genes in heatmap

### ISSUE THREAD

**Issue by okendojo** [praneet1988/CSBB-Shiny#1]
IS there a way in which one can select only a given number of genes in the heatmap plot? For example if I only one to look at top 30 genes in my sample how can I do this? I suggest you add a function for this and I must admit that this is a great tool and it will help people to understand their data very easily

**Comment by praneet1988** [comment]
Dear Javan,
Thank you for raising this issue. I will definitely get this into CSBB version 1.2. For now, one way to get the heatmap for selected set of genes of interest (GOI) is by sub-setting the expression matrix for GOI and then use visualization module. Also, Differential expression module helps you directly visualize DE genes based on your cutoffs for LogFC and FDR in heatmap, volcano plot, tsne, and pca.

Hope this helps.

Best Regards,
Praneet

**Comment by okendojo** [comment]
Dear Praneet,

Thanks for this clarification. You have made a simple and easy to use tool
for non-bioinformatics data analysis. I like the use of FDR function. Let
me know once you have the version 1.2.

Regards,
Javan Okendo
