### ISSUE TITLE
Server error.

### ISSUE THREAD

**Issue by ambuvjyn** [praneet1988/CSBB-Shiny#3]
When plotting graphs, its showing server error. I used test data and its not showing anything. Is it some error from my side?
Do i have to use any specific browser?

**Comment by praneet1988** [comment]
Dear Ambu,
Good Morning. It seems that you might be using the link to access the app which doesn't have enough ram to support operations. Please use Commands mentioned in the readme to launch CSBB-Shiny from RStudio.

Hope this helps.

Best,
Praneet

**Comment by ambuvjyn** [comment]
I will try that, Thanks @praneet1988
